### PR TITLE
Telephony: Conditionally ignore RSSNR signal level

### PR DESCRIPTION
**Pull request by lucasponez**
Avoid 0% signal of LTE.

### CODE REVIEW

**Review by Jorg3Lucas — CHANGES_REQUESTED** [review]
Please, before pushing a pull request, give the authorship to the true author of the commit.
How Add correct authorship ?
Git commit--amend--author =  "Name <email> "

**Comment by henriquee0023** [comment]
CypherOS/frameworks_base@6ba5eb1 oh damn

**Comment by lucasponez** [comment]
Even you send me an incorrect code, I'm so glad. Thank you for advice.

**Comment by Jorg3Lucas** [comment]
> Even you sent me an incorrect code, I'm so glad. Thank you for advice.

I sent it correctly but did not appear in the preview of the comment.

**Comment by lucasponez** [comment]
Thank you one more time, anyway.

**Pull request closed without merging**
