### PR TITLE
networkClassToString invalid input

### PR DESCRIPTION
**Pull request by richmonkeys**
My systemui crashed and the below is the logcat.
-------------------------------------------------------------
FATAL EXCEPTION: main
Process: com.android.systemui, PID: 29537
android.content.res.Resources$NotFoundException: String resource ID #0x0
	at android.content.res.Resources.getText(Resources.java:335)
	at android.content.res.Resources.getString(Resources.java:381)
	at com.android.keyguard.CarrierText.networkClassToString(CarrierText.java:433)
	at com.android.keyguard.CarrierText.updateCarrierText(CarrierText.java:131)
	at com.android.keyguard.CarrierText$1.onRefreshCarrierInfo(CarrierText.java:59)
	at com.android.keyguard.KeyguardUpdateMonitor.sendUpdates(KeyguardUpdateMonitor.java:1549)
	at com.android.keyguard.KeyguardUpdateMonitor.registerCallback(KeyguardUpdateMonitor.java:1540)
	at com.android.keyguard.CarrierText.onAttachedToWindow(CarrierText.java:240)
-------------------------------------------------------------

The proposed PR is to check if networkClass value is within the array.
I'm not a java coder. There might be better code for this but I believe at least this will work.

Please kindly refer to attached image for context.

2016-11-28-network-1

### CODE REVIEW

**Comment by xyyx** [comment]
How to get this error? I don't have this crash.

**Comment by richmonkeys** [comment]
Hi xyyx,
I am not sure how it happens. It could be my SIM card, telco, or baseband.
If I switch to GSM only it is fine.

At least the PR will verify if the value exists in the array, returns empty string if it doesn't, and stop crashing.

EDIT:
Sorry I didn't answer your question earlier, it actually happens while waking up my phone from sleep.
The cause is unknown.

**Comment by xyyx** [comment]
Did this patch fix it? What device do you have? 
networkClassToString(TelephonyManager.getNetworkClass(networkType));

I think it's operator's problem. But I'll merge it. Thanks

**Comment by richmonkeys** [comment]
I'm sorry looks like TelephonyManager.getNetworkClass(networkType) is returning 0 if it is invalid.
Seems like the PR will not fix the crash.

function:
https://android.googlesource.com/platform/frameworks/base/+/android-7.1.0_r1/telephony/java/android/telephony/TelephonyManager.java#1680

return:
https://github.com/nitrogen-project/android_frameworks_base/blob/n2/telephony/java/android/telephony/TelephonyManager.java#L1692

getContext().getResources().getString(classIds[networkClass])
getContext().getResources().getString(classIds[0])
getContext().getResources().getString(0)

This should be the real fix:
https://osdn.net/projects/android-x86/scm/git/frameworks-base/commits/b99261ab27fff4d9b7a81b8be28e5dd48963ce35

The current PR can be kept intact. I will create another patch for this, and maybe another PR for the resource value.

Sorry for the trouble.

**Comment by xyyx** [comment]
Device?

**Comment by richmonkeys** [comment]
My device is Xiaomi Mi 3w. Ported by Shahan_mik3 http://forum.xda-developers.com/xiaomi-mi-3/development/rom-nitrogen-os-n-substratum-23-09-2016-t3467316/

My device might not be officially supported but I believe this UNKNOWN_NETWORK crash should be fixed.

**Pull request merged**
